from selenium.webdriver.common.by import By

SING_IN = (By.XPATH, ".//button[text() = 'Вход и регистрация']")
NO_ACC = (By.XPATH, ".//button[text() = 'Нет аккаунта']")
EMAIL = (By.XPATH, ".//input[@placeholder = 'Введите Email']")
PASSWORD = (By.XPATH, ".//input[@placeholder = 'Пароль']")
REPEAT_PASSWORD = (By.XPATH, ".//input[@placeholder = 'Повторите пароль']")
CREATE_ACC = (By.XPATH, ".//button[text() = 'Создать аккаунт']")
AVATAR_USER = (By.XPATH, ".//button[@class = 'circleSmall']")
USER_NAME = (By.XPATH, ".//h3[@class = 'profileText name']")
ERROR_EMAIL = (By.XPATH, "//div[contains(@style, '472')]/div[contains(@class, 'in')]")
ERROR_PASSWORD = (By.XPATH, "//input[@placeholder = 'Пароль']/parent::div")
ERROR_REPEAT_PASSWORD = (By.XPATH, "//input[@placeholder = 'Повторите пароль']/parent::div")
ERROR_MESSAGE = (By.XPATH, ".//span[text()='Ошибка']")
LOGIN = (By.XPATH, ".//button[text()='Войти']")
LOG_OUT = (By.XPATH, ".//button[text()='Выйти']")
PLACE_AN_AD = (By.XPATH, ".//button[text()='Разместить объявление']")
MODAL_WINDOW = (By.XPATH, ".//h1[text()='Чтобы разместить объявление, авторизуйтесь']")
NAME_AD = (By.XPATH, ".//input[@placeholder = 'Название']")
DESCR = (By.XPATH, ".//textarea[@placeholder = 'Описание товара']")
PRICE = (By.XPATH, ".//input[@placeholder = 'Стоимость']")
DROPDOWN_BUTTON_CATEGORY = (By.XPATH, ".//div[contains(@style, '984')]/button")
CATEGORY_SADOVOD = (By.XPATH, ".//span[text()='Садоводство']")
DROPDOWN_BUTTON_CITY = (By.XPATH, ".//div[contains(@style, '760')]/button")
CITY_SPB = (By.XPATH,".//span[text()='Санкт-Петербург']")
RADIO_BUTTON_BU = (By.XPATH,".//div[@class='radioUnput_inputRegular__FbVbr']")
POST_AD = (By.XPATH,".//button[text()='Опубликовать']")
CARD_AD_PRICE = (By.XPATH,".//div[@class = 'price']/h2")
NEXT_BUTTON = (By.XPATH,".//button[@class = 'arrowButton arrowButton--right undefined']")